---
title: "Reproducible report of the figures"
output:
  html_document:
    df_print: paged
  html_notebook:
    fig_caption: yes
    fig_height: 7
    fig_width: 10
    highlight: tango
    theme: readable
---
```{r setup, include=FALSE, message=FALSE}
library(tidyverse, quietly = T, warn.conflicts = FALSE)
library(data.table)
library(extrafont)
library(gridExtra)
library(latex2exp)
knitr::opts_chunk$set(message = FALSE, warning=FALSE, cache = FALSE,
                      fig.path="figures/", dev=c('png', 'pdf'),
                      echo = FALSE, fig.height = 12, fig.width = 16)
knitr::opts_knit$set(eval.after = "fig.cap")
caption <- "generic caption"
```

```{r load_data, include=FALSE}
csize <- 100 #max cohort size
files <- list.files(path = here::here("results"), pattern = "McF.*\\.result\\.csv", full.names = T)
big_table <- lapply(files, read_csv) %>% bind_rows() %>% filter(!is.na(s_pos), s_neg>=-1) %>% as.data.table
```

```{r}
big_table[,rep := 1:.N, by=c("s_pos","s_neg")]
big_table[,cohort := ceiling(rep/csize)]
colnames(big_table) <- colnames(big_table) %>% str_replace("_deletereous","_deleterious")
```


```{r}
# Progression plot
prog_data <-big_table[rep<=3000 & s_pos>0 & s_neg<0,.(Time, tumor_size, n_clones, largest_clone),by=c("s_pos","s_neg","cohort")] 
mean_prog <- prog_data[,lapply(.SD, mean), by=c("s_pos")]
```




```{r fig-prog, fig.height=8, fig.width=16, fig.cap=caption, dev=c("png","pdf")}

fp1 <-prog_data %>%
  ggplot(aes(x=as.factor(s_pos),y=log10(Time), fill=as.factor(s_neg))) +
    geom_boxplot(outlier.size=1, outlier.color = NA, outlier.shape = 21) +
    ggpubr::theme_pubr(base_size = 20)+
    ggsci::scale_fill_nejm() +
    theme(axis.text.x = element_text(angle = 45, vjust = 0.47)) +
    theme(legend.position = "bottom") +
    labs(y="logartimic time", x="s+", fill="      s-", subtitle = "Progression time")
fp2 <-prog_data %>%
  ggplot(aes(x=as.factor(s_pos),y=n_clones, fill=as.factor(s_neg))) +
    geom_boxplot(outlier.size=1, outlier.color = NA, outlier.shape = 21) +
    ggpubr::theme_pubr(base_size = 20)+
    ggsci::scale_fill_nejm() +
    theme(axis.text.x = element_text(angle = 45, vjust = 0.47)) +
  
    theme(legend.position = "none") +
    ylim(c(0,10)) +
    labs(y="number of clones", x="s+", fill="      s-", subtitle = "Number of clones")
fp3 <-prog_data %>%
  ggplot(aes(x=as.factor(s_pos),y=largest_clone, fill=as.factor(s_neg))) +
    geom_boxplot(outlier.size=1, outlier.color = NA, outlier.shape = 21) +
    ggsci::scale_fill_nejm() +
    ggpubr::theme_pubr(base_size = 20)+
    theme(axis.text.x = element_text(angle = 45, vjust = 0.47)) +
    theme(legend.position = "none") +
    ylim(c(0,1)) +
    labs(y="proportion of tumor size", x="s+", fill="      s-", subtitle = "Largest clone")


ggpubr::ggarrange(fp1,fp2,fp3, nrow=1, legend = "bottom", common.legend = TRUE)

caption <- "Parameters obtained at the end of the tumor progression for the different scenarios. Growth time represents the time, in decimal logarithmic scale, that the tumor took to reach the size of $10^7$ cells. The number of clones indicates the final number of clones present in the tumor, considering as clones the different genotypes with positive mutations present. The largest clone shows the proportion of the size of the tumor that occupies the majority clone."
```

```{r}
cohort_table <- big_table[rep<=3000 & s_pos>0, 
                          .(N_driver=sum(N_driver), S_driver=sum(S_driver),N_neutral=sum(N_neutral), S_neutral=sum(S_neutral),N_deleterious=sum(N_deleterious), S_deleterious=sum(S_deleterious),
                            sp_N_driver=sum(sp_N_driver), sp_S_driver=sum(sp_S_driver), sp_N_neutral=sum(sp_N_neutral), sp_S_neutral=sum(sp_S_neutral),sp_N_deleterious=sum(sp_N_deleterious), sp_S_deleterious=sum(sp_S_deleterious),
                            cl_N_driver=sum(cl_N_driver), cl_S_driver=sum(cl_S_driver),cl_N_neutral=sum(cl_N_neutral), cl_S_neutral=sum(cl_S_neutral),cl_N_deleterious=sum(cl_N_deleterious), cl_S_deleterious=sum(cl_S_deleterious)),by=c("s_pos","s_neg","cohort") ]
```

```{r}
cohort_table[,`:=`(pNpS_driver=N_driver/S_driver, pNpS_neutral=N_neutral/S_neutral, pNpS_deleterious=N_deleterious/S_deleterious, pNpS_mix= (N_driver + N_deleterious)/(S_driver + S_deleterious))]
cohort_table[,`:=`(sp_pNpS_driver=sp_N_driver/sp_S_driver, sp_pNpS_neutral=sp_N_neutral/sp_S_neutral, sp_pNpS_deleterious=sp_N_deleterious/sp_S_deleterious, sp_pNpS_mix= (sp_N_driver + sp_N_deleterious)/(sp_S_driver + sp_S_deleterious))]
cohort_table[,`:=`(cl_pNpS_driver=cl_N_driver/cl_S_driver, cl_pNpS_neutral=cl_N_neutral/cl_S_neutral, cl_pNpS_deleterious=cl_N_deleterious/cl_S_deleterious, cl_pNpS_mix= (cl_N_driver + cl_N_deleterious)/(cl_S_driver + cl_S_deleterious))]
cohort_table[,lapply(.SD, mean), by=c("s_pos","s_neg")]
```


```{r}
pnps_table <- cohort_table[s_neg < 0,.(pNpS_driver,pNpS_neutral,pNpS_deleterious,pNpS_mix, sp_pNpS_driver,sp_pNpS_neutral,sp_pNpS_deleterious,sp_pNpS_mix, cl_pNpS_driver,cl_pNpS_neutral,cl_pNpS_deleterious, cl_pNpS_mix), by=c("s_pos","s_neg")] %>% melt(id.vars = c("s_pos","s_neg"), value.name="pN_pS")
```




```{r fig-pnps, fig.height=15, fig.width=15}
ind_plot <- function(X,y1=0,y2=2, tit){
  X %>%
    ggplot(aes(x=s_pos, color=as.factor(s_neg)))+
      geom_line(aes(y=mean)) +
      geom_errorbar(aes(ymin=mean-se,ymax=mean+se), width=0.02) +
      ggsci::scale_color_nejm() +
      ggpubr::theme_pubr(base_size = 20)+
      geom_hline(yintercept = 1, lty="dashed") +
      labs(y=TeX("pN/pS"), x=TeX("$s^+$}"), color=TeX("      $s^-$"), title=tit) +
      ylim(c(y1,y2))+
      theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
      theme(plot.title = element_text(face = "bold", size=18))
  
  
}

f1 <- pnps_table[variable=="pNpS_driver",.(mean=mean(pN_pS, na.rm = T),se=2*sd(pN_pS, na.rm = T)/sqrt(.N)),by=c("s_pos","s_neg")] %>% ind_plot(y1=0,y2=2, TeX('I. Driver gene, $pN/pS_{all}$'))
f2 <- pnps_table[variable=="pNpS_neutral",.(mean=mean(pN_pS, na.rm = T),se=2*sd(pN_pS, na.rm = T)/sqrt(.N)),by=c("s_pos","s_neg")] %>% ind_plot(y1=0,y2=2, TeX('G. Neutral gene, $pN/pS_{all}$'))
f3 <- pnps_table[variable=="pNpS_deleterious",.(mean=mean(pN_pS, na.rm = T),se=2*sd(pN_pS, na.rm = T)/sqrt(.N)),by=c("s_pos","s_neg")] %>% ind_plot(y1=0,y2=2, TeX( 'H. Deleterious gene, $pN/pS_{all}$'))
f4 <- pnps_table[variable=="sp_pNpS_driver",.(mean=mean(pN_pS, na.rm = T),se=2*sd(pN_pS, na.rm = T)/sqrt(.N)),by=c("s_pos","s_neg")] %>% ind_plot(y1=0,y2=60, TeX( 'C. Driver gene, $pN/pS_{subclonal}$'))
f5 <- pnps_table[variable=="sp_pNpS_neutral",.(mean=mean(pN_pS, na.rm = T),se=2*sd(pN_pS, na.rm = T)/sqrt(.N)),by=c("s_pos","s_neg")] %>% ind_plot(y1=0,y2=2,  TeX( 'A. Neutral gene, $pN/pS_{subclonal}$'))
f6 <- pnps_table[variable=="sp_pNpS_deleterious",.(mean=mean(pN_pS, na.rm = T),se=2*sd(pN_pS, na.rm = T)/sqrt(.N)),by=c("s_pos","s_neg")] %>% ind_plot(y1=0,y2=2, TeX( 'B. Deleterious gene, $pN/pS_{subclonal}$'))
f7 <- pnps_table[variable=="cl_pNpS_driver",.(mean=mean(pN_pS, na.rm = T),se=2*sd(pN_pS, na.rm = T)/sqrt(.N)),by=c("s_pos","s_neg")] %>% ind_plot(y1=0,y2=60, TeX( 'F. Driver gene, $pN/pS_{clonal}$'))
f8 <- pnps_table[variable=="cl_pNpS_neutral",.(mean=mean(pN_pS, na.rm = T),se=2*sd(pN_pS, na.rm = T)/sqrt(.N)),by=c("s_pos","s_neg")] %>% ind_plot(y1=0,y2=2, TeX( 'D. Neutral gene, $pN/pS_{clonal}$'))
f9 <- pnps_table[variable=="cl_pNpS_deleterious",.(mean=mean(pN_pS, na.rm = T),se=2*sd(pN_pS, na.rm = T)/sqrt(.N)),by=c("s_pos","s_neg")] %>% ind_plot(y1=0,y2=2, TeX( 'E. Deleterious gene, $pN/pS_{clonal}$'))
f10 <- pnps_table[variable=="pNpS_mix",.(mean=mean(pN_pS, na.rm = T),se=2*sd(pN_pS, na.rm = T)/sqrt(.N)),by=c("s_pos","s_neg")] %>% ind_plot(y1=0,y2=2, TeX( 'C. Mixed gene, $pN/pS_{all}$'))
f11 <- pnps_table[variable=="sp_pNpS_mix",.(mean=mean(pN_pS, na.rm = T),se=2*sd(pN_pS, na.rm = T)/sqrt(.N)),by=c("s_pos","s_neg")] %>% ind_plot(y1=0,y2=60, TeX( 'A. Mixed gene, $pN/pS_{subclonal}$'))
f12 <- pnps_table[variable=="cl_pNpS_mix",.(mean=mean(pN_pS, na.rm = T),se=2*sd(pN_pS, na.rm = T)/sqrt(.N)),by=c("s_pos","s_neg")] %>% ind_plot(y1=0,y2=60, TeX( 'B. Mixed gene, $pN/pS_{clonal}$'))
ggpubr::ggarrange(f5,f6, f4, f8,f9,f7,  f2,f3,f1, 
                  nrow = 3, ncol=3, common.legend = TRUE, heights = c(4,4,4)
                 )


```

```{r fig-mixedGene, fig.height=5, fig.width=15}
ggpubr::ggarrange(f11,f12,f10, 
                  nrow = 1, ncol=3, common.legend = TRUE, heights = c(4,4,4)
                 )
```


## VAF

```{r load-freqs}
freqsQ <- fread(here::here("results","s_freqs_merged.csv"))
```

```{r}
# Temp.
files2 <- list.files(path = here::here("results"), pattern = "McF_31\\.freqs\\.csv", full.names = T)
freqs <- lapply(files2, read_csv, col_names=FALSE) %>% bind_rows()
```

```{r}
q <- freqs[1:100,1:3000] %>% as.matrix %>% as.numeric
nq <- 100
tFreqs <- data.frame(q=q, 
                      gene=factor(c(rep("driver",nq*1000),rep("deleterious",nq*1000),rep("neutral",nq*1000)), 
                                 levels = c("neutral","deleterious","driver")),
                      mutation=factor(c(rep("N",nq*500),rep("S",nq*500),rep("N",nq*500),rep("S",nq*500),rep("N",nq*500),rep("S",nq*500)), 
                                 levels = c("N","S")))
```

```{r}
examplePNPS <- as.data.table(tFreqs)[q>0,.N, by=c("gene","mutation")] %>% 
                              dcast(gene ~ mutation) %>% 
                              mutate(pNpSall=N/S) %>% 
                              select(gene,pNpSall) %>%
                left_join( as.data.table(tFreqs)[q>0.05,.N, by=c("gene","mutation")] %>%
                             dcast(gene ~ mutation) %>% 
                             mutate(pNpSdet=N/S) %>% 
                             select(gene,pNpSdet) ) %>%
                left_join( as.data.table(tFreqs)[q==1,.N, by=c("gene","mutation")] %>%
                             dcast(gene ~ mutation) %>% 
                             mutate(pNpSclon=N/S) %>% 
                             select(gene,pNpSclon) ) 

```


```{r fig-VAF-example, fig.height=6, fig.width=12, fig.cap = caption}
tFreqs %>% 
  filter(q>0) %>% 
  ggplot(aes(x=q, fill=mutation)) + 
    #geom_histogram(bins=11) +
  geom_bar(position = "stack") +
    scale_x_binned(breaks = seq(0.05,0.95, by = 0.05),
                   labels = c(".05","",".15","",".25","",".35","",".45","",".55","",".65","",".75","",".85","",".95"))+
    
    facet_wrap(~gene) +
  
  geom_text(data = examplePNPS, mapping = aes(x=0.8, y=30000, fill=NULL, 
              label=TeX('$\\textit{pN/pS_{all}}$ = ', output = "character")),
              vjust = 1, hjust=1, size=5, parse=T) +
  geom_text(data = examplePNPS, mapping = aes(x=0.8, y=30000, fill=NULL, 
              label=sprintf(" %.02f",pNpSall)),
              vjust = 1, hjust=0, size=5, parse=T) +
  geom_text(data = examplePNPS, mapping = aes(x=0.8, y=26000, fill=NULL, 
              label=TeX('$\\textit{pN/pS_{subclonal}}$ = ', output = "character")),
              vjust = 1, hjust=1, size=5, parse=T) +
  geom_text(data = examplePNPS, mapping = aes(x=0.8, y=26000, fill=NULL, 
              label=sprintf(" %.02f",pNpSdet)),
              vjust = 1, hjust=0, size=5, parse=T) +
  geom_text(data = examplePNPS, mapping = aes(x=0.8, y=22000, fill=NULL, 
              label=TeX('$\\textit{pN/pS_{clonal}}$ = ', output = "character")),
              vjust = 1, hjust=1, size=5, parse=T) +
  geom_text(data = examplePNPS, mapping = aes(x=0.8, y=22000, fill=NULL, 
              label=sprintf(" %.02f",pNpSclon)),
              vjust = 1, hjust=0, size=5, parse=T) +
  
    labs(x="Frequency", y="ocurrences in cohort", color="mutation type", title=latex2exp::latex2exp("$\\textit{s^+} = 0.1$, $\\textit{s^-} = -0.25$, 1 cohort 100 tumors")) +
    ggpubr::theme_pubr(base_size = 18) +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
caption <- "Variant allele in a cohort of 1000 tumors for the $s^+$ = 0.1 and $s^-$ = -0.25 scenario."
```

## Relationship between selection coefficient and pN/pS
```{r}
cohort_size <- 100
freqs <- fread(here::here("results","s_freqs_merged.csv"))
#Limit to 3000 replicates,as some cases could have a couple more of them 
freqs <- freqs[, head(.SD,3000), by=V1002]
colnames(freqs) <- c("s", rep("N",500), rep("S",500),"id", rep("kk",4))
freqs[, rep := 1:.N, by="s"]
freqs[,cohort := ceiling(rep/cohort_size)]
freqs <- data.table::melt(freqs, id.vars = c("s","cohort"), measure.vars = 2:1001, variable.name = "mutation", value.name = "q")

```

```{r}
t_pNpS_s <- freqs[(s>-1),.(m0=sum(q>0),m01=sum(q>=0.001),m5=sum(q>=0.05),m100=sum(q==1)),by=.(s,mutation,cohort)] %>% 
  dcast(s+cohort~mutation, value.var=c("m0","m01","m5","m100")) %>%
  .[,.(s, pNpS_0 = m0_N/m0_S, pNpS_0.001 = m01_N/m01_S, pNpS_0.05 = m5_N/m5_S, pNpS_1 = m100_N/m100_S)] %>%
  data.table::melt(id.vars = "s", measure = patterns("^pNpS_"), variable.name="mutations", value.name="pN_pS") 
setattr(t_pNpS_s[["mutations"]],"levels",c("all", "subclonal0.001", "subclonal0.05", "clonal"))
```

```{r fig-selection-log, fig.height=6, fig.width=10}
t_pNpS_s[,.(mean=mean(pN_pS, na.rm = T),se=2*sd(pN_pS, na.rm = T)/sqrt(.N)),by=c("s","mutations")] %>% 
  ggplot(aes(x=s, color=as.factor(mutations)))+
    geom_line(aes(y=mean)) +
    geom_errorbar(aes(ymin=mean-se,ymax=mean+se), width=0.02) +
    ggsci::scale_color_nejm() +
    ggpubr::theme_pubr(base_size=16)+
    geom_vline(xintercept = 0, lty="dashed") +
    labs(y="pN/pS", x=TeX("s"), color="      mutations")+
  scale_y_continuous(trans='log10') +
    #coord_trans(y="log10")+
    geom_hline(yintercept = 1, lty="dashed") +
    #ylim(c(-1,10)) +
    theme(plot.title = element_text(face = "bold", size=14))
```

```{r}
t_pNpS_s[mutations=="all" & s>=0, .(pnps=mean(pN_pS)), by="s"]
t_pNpS_s[mutations=="all" & s>=0.05,] %>% lm(pN_pS~s,data = .) %>% summary()
```



```{r}
facet.labs <- c("s = -0.75","s = -0.05","s = 0", "s = 0.05", "s = 0.75", "s = 2")
names(facet.labs) <- c(-0.75,-0.05,0,0.05,0.75,2)
p1<-freqs[q>0 & (s==-0.75 | s==-0.05 | s==0 | s==0.05 |  s==0.75 | s== 2)] %>% 
    ggplot(aes(x=q, fill=mutation)) + 
    geom_bar(position = "stack") +
    scale_x_binned(breaks = seq(0.05,0.95, by = 0.05),
                   labels = c(".05","",".15","",".25","",".35","",".45","",".55","",".65","",".75","",".85","",".95"))+
    ggpubr::theme_pubr(base_size = 20) +
    facet_grid(s ~., scales = "free_y", labeller = labeller(s = facet.labs)) +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
    labs(subtitle="All", x="Frequency")
p2<-freqs[q>0.05 & (s==-0.75 | s==-0.05 | s==0 | s==0.05 | s==0.75 | s== 2)] %>% 
    ggplot(aes(x=q, fill=mutation)) + 
    geom_bar(position = "stack") +
    scale_x_binned(breaks = seq(0.1,0.95, by = 0.05),
                   labels = c("",".15","",".25","",".35","",".45","",".55","",".65","",".75","",".85","",".95"))+
    ggpubr::theme_pubr(base_size = 20) +
    facet_grid(s ~., scales = "free_y", labeller = labeller(s = facet.labs)) +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
    labs(subtitle="Subclonal", x="Frequency")
ggpubr::ggarrange(p1,p2, common.legend = TRUE, legend = "top" )
```






```{r select-s}
dcast(t_pNpS_s,s~mutations) %>%
  knitr::kable(digits = 2,caption = "Average pN/pS for different s and threshold frequencies",booktabs=TRUE) %>%
  kableExtra::kable_styling(full_width = FALSE)

```

# Time

```{r}
# Get the new data in files time_s_pos_XX_pY.{result|freqs}.csv and combine them
# in a big data.table
freq_files <- list.files(path = here::here("results"), pattern='time_s_pos_.*_p.*freqs',full.names = TRUE)
res_files <- list.files(path = here::here("results"), pattern='time_s_pos_.*_p.*result',full.names = TRUE)

hrep <- str_extract(res_files,'_p[0-9]*\\.') %>% parse_number()
dt_res <- rbindlist(setNames(lapply(res_files, fread, select = c(29,35 ,34, 23, 27), col.names = c("s", "rep","threshold_size","true_size","time") ), hrep), idcol = "hrep")
hrep <- str_extract(res_files,'_p[0-9]*\\.') %>% parse_number()
dt_freq <- rbindlist(setNames(lapply(freq_files, fread, col.names = c(rep("N",500), rep("S",500),"id", "s", rep("kk",4), "threshold_size", "rep")), hrep), idcol = "hrep")

# Combine datatables
full_data <- dt_res[dt_freq, on= c("s","hrep","rep","threshold_size")]

#Clean data
full_data <- full_data[,-c("id", "kk", "kk.1", "kk.2", "kk.3")]
full_data[,threshold_size := log10(threshold_size)]
full_data[,true_size := log10(true_size)]
full_data[,rep := as.numeric(factor(paste(hrep,rep,sep="_"))),by=s]
rm(list = c("dt_freq","dt_res"))
```

```{r}
# Number of replicates
 full_data[,.N,by=c("s","threshold_size")] %>% dcast(s ~ threshold_size, value.var="N")
```


```{r}
cohort_size <- 100
time_points <- 6 
# Remove incomplete replicates
wdt <-  full_data[threshold_size<=(time_points+1)][,full_rep := .N>=time_points, by=c("s","rep")]
rm(full_data)
wdt[, rel_time := time - .SD[1,time], by=c("s","rep")]
wdt <- wdt[which(full_rep==TRUE)]

# Some replicates can fail in the last point, remove them
if(time_points == 7){
  wdt[, wrong := (.SD[7,time] - .SD[6,time] < 0), by=c("s","rep")]
  wdt <- wdt[which(wrong==FALSE)]
} else{
  wdt[,wrong := FALSE]
}


# Renumber valid replicates
wdt[, rep := 1:.N, by=c("s","threshold_size")]
setcolorder(wdt, c("s","rep"))

# Limit to 10K replicates
wdt <- wdt[rep<=10000]
# Create cohorts (100 tumors)
wdt[,cohort := ceiling(rep/cohort_size)]

# discard incomplete cohorts
wdt[, full_cohort := .N==cohort_size, by=c("s","cohort", "threshold_size")]
wdt <- wdt[full_cohort == TRUE,][,c("full_cohort","hrep","full_rep","wrong") := NULL]


#Calculate relative time (relative to N=10^2)
setcolorder(wdt, c("s","cohort", "rep", "threshold_size", "true_size", "time", "rel_time"))

```

```{r}
wdt[,.(cohorts=max(cohort)),by=c("s")] 
```



```{r}
#clonal, replicate by replicate, then summarizing by cohort
clonal <- wdt[,.(s, cohort, rep, threshold_size, true_size, time, rel_time, Nmuts= apply(wdt[,which(grepl("^N.*$", colnames(wdt))), with=FALSE], 1, function(X){sum(X==1)}), Smuts= apply(wdt[,which(grepl("^S.*$", colnames(wdt))), with=FALSE], 1, function(X){sum(X==1)}))][, .(true_size=mean(true_size), rel_time=mean(rel_time, na.rm = T), Nmuts = mean(Nmuts), Smuts = mean(Smuts)), by = c("s","cohort","threshold_size")][,pNpS := Nmuts/Smuts]

```

```{r}
#clonal, replicate by replicate, then summarizing by cohort
segregating <- wdt[,.(s, cohort, rep, threshold_size, true_size, time, rel_time, Nmuts= apply(wdt[,which(grepl("^N.*$", colnames(wdt))), with=FALSE], 1, function(X){sum(X>=0.05)}), Smuts= apply(wdt[,which(grepl("^S.*$", colnames(wdt))), with=FALSE], 1, function(X){sum(X>=0.05)}))][, .(true_size=mean(true_size), rel_time=mean(rel_time, na.rm = T), Nmuts = mean(Nmuts), Smuts = mean(Smuts)), by = c("s","cohort","threshold_size")][,pNpS := Nmuts/Smuts]

```

```{r}
#clonal, replicate by replicate, then summarizing by cohort
all <- wdt[,.(s, cohort, rep, threshold_size, true_size, time, rel_time, Nmuts= apply(wdt[,which(grepl("^N.*$", colnames(wdt))), with=FALSE], 1, function(X){sum(X>0)}), Smuts= apply(wdt[,which(grepl("^S.*$", colnames(wdt))), with=FALSE], 1, function(X){sum(X>0)}))][, .(true_size=mean(true_size), rel_time=mean(rel_time, na.rm = T), Nmuts = mean(Nmuts), Smuts = mean(Smuts)), by = c("s","cohort","threshold_size")][,pNpS := Nmuts/Smuts]

```




```{r}
panI <- all[,.(mean=mean(Nmuts),se=2*sd(Nmuts)/sqrt(.N)),by=c("s","threshold_size")] %>%
  ggplot(aes(x=threshold_size,  color=as.factor(s))) + 
    geom_line(aes(y=mean)) +
    geom_errorbar(aes(ymin=mean-se,ymax=mean+se), width=0.1) +
    ggsci::scale_color_nejm() +
    ggpubr::theme_pubr(base_size=16, legend = "none") +
    labs(y="N", x=TeX("log_{10}(cells)"), color="      s", title= TeX("\\textbf{I.} All non-synonymous")) +
    theme(plot.title = element_text(face = "bold", size=14))
  
panH <- all[,.(mean=mean(Smuts),se=2*sd(Smuts)/sqrt(.N)),by=c("s","threshold_size")] %>%
  ggplot(aes(x=threshold_size,  color=as.factor(s))) + 
    geom_line(aes(y=mean)) +
    geom_errorbar(aes(ymin=mean-se,ymax=mean+se), width=0.1) +
    ggsci::scale_color_nejm() +
    ggpubr::theme_pubr(base_size=16, legend = "none", ) +
    labs(y="S", x=TeX("log_{10}(cells)"), color="      s", title= TeX("\\textbf{H.} All synonymous"))  +
    theme(plot.title = element_text(face = "bold", size=14))

panG <- all[,.(mean=mean(pNpS),se=2*sd(pNpS)/sqrt(.N)),by=c("s","threshold_size")] %>%
  ggplot(aes(x=threshold_size,  color=as.factor(s))) + 
    geom_line(aes(y=mean)) +
    geom_errorbar(aes(ymin=mean-se,ymax=mean+se), width=0.1) +
    ggsci::scale_color_nejm() +
    ggpubr::theme_pubr(base_size=16, legend = "none") +
    labs(y="pN/pS", x=TeX("log_{10}(cells)"), color="      s", title= TeX("\\textbf{G.} $pN/pS_{all}$"))  +
    geom_hline(yintercept = 1, lty="dashed") +
    ylim(c(0,50)) +
    theme(plot.title = element_text(face = "bold", size=14))

panC <- segregating[,.(mean=mean(Nmuts),se=2*sd(Nmuts)/sqrt(.N)),by=c("s","threshold_size")] %>%
  ggplot(aes(x=threshold_size,  color=as.factor(s))) + 
    geom_line(aes(y=mean)) +
    geom_errorbar(aes(ymin=mean-se,ymax=mean+se), width=0.1) +
    ggsci::scale_color_nejm() +
    ggpubr::theme_pubr(base_size=16, legend = "none") +
    labs(y="N", x=TeX("log_{10}(cells)"), color="      s", title= TeX("\\textbf{C.} Subclonal non-synonymous"))  +
    theme(plot.title = element_text(face = "bold", size=14))
  
panB <- segregating[,.(mean=mean(Smuts),se=2*sd(Smuts)/sqrt(.N)),by=c("s","threshold_size")] %>%
  ggplot(aes(x=threshold_size,  color=as.factor(s))) + 
    geom_line(aes(y=mean)) +
    geom_errorbar(aes(ymin=mean-se,ymax=mean+se), width=0.1) +
    ggsci::scale_color_nejm() +
    ggpubr::theme_pubr(base_size=16, legend = "none") +
    labs(y="S", x=TeX("log_{10}(cells)"), color="      s", title= TeX("\\textbf{B.} Subclonal synonymous$")) +
    theme(plot.title = element_text(face = "bold", size=14))

panA <- segregating[,.(mean=mean(pNpS),se=2*sd(pNpS)/sqrt(.N)),by=c("s","threshold_size")] %>%
  ggplot(aes(x=threshold_size,  color=as.factor(s))) + 
    geom_line(aes(y=mean)) +
    geom_errorbar(aes(ymin=mean-se,ymax=mean+se), width=0.1) +
    ggsci::scale_color_nejm() +
    ggpubr::theme_pubr(base_size=16, legend = "none") +
    labs(y="pN/pS", x=TeX("log_{10}(cells)"), color="      s", title= TeX("\\textbf{A.} $pN/pS_{subclonal}$")) +
    geom_hline(yintercept = 1, lty="dashed") +
    ylim(c(0,100)) +
    theme(plot.title = element_text(face = "bold", size=14))

panF <- clonal[,.(mean=mean(Nmuts),se=2*sd(Nmuts)/sqrt(.N)),by=c("s","threshold_size")] %>%
  ggplot(aes(x=threshold_size,  color=as.factor(s))) + 
    geom_line(aes(y=mean)) +
    geom_errorbar(aes(ymin=mean-se,ymax=mean+se), width=0.1) +
    ggsci::scale_color_nejm() +
    ggpubr::theme_pubr(base_size=16, legend = "none") +
    labs(y="N", x=TeX("log_{10}(cells)"), color="      s", title= TeX("\\textbf{F.} Clonal non-synonymous")) +
    theme(plot.title = element_text(face = "bold", size=14))
  
panE <- clonal[,.(mean=mean(Smuts),se=2*sd(Smuts)/sqrt(.N)),by=c("s","threshold_size")] %>%
  ggplot(aes(x=threshold_size, color=as.factor(s))) + 
    geom_line(aes(y=mean)) +
    geom_errorbar(aes(ymin=mean-se,ymax=mean+se), width=0.1) +
    ggsci::scale_color_nejm() +
    ggpubr::theme_pubr(base_size=16, legend = "none") +
    labs(y="S", x=TeX("log_{10}(cells)"), color="      s", title= TeX("\\textbf{E.} Clonal synonymous")) +
    theme(plot.title = element_text(face = "bold", size=14))

panD <- clonal[,.(mean=mean(pNpS),se=2*sd(pNpS)/sqrt(.N)),by=c("s","threshold_size")] %>%
  ggplot(aes(x=threshold_size, color=as.factor(s))) + 
    geom_line(aes(y=mean)) +
    geom_errorbar(aes(ymin=mean-se,ymax=mean+se), width=0.1) +
    ggsci::scale_color_nejm() +
    ggpubr::theme_pubr(base_size=16, legend = "none") +
    labs(y="pN/pS", x=TeX("log_{10}(cells)"), color="      s", title= TeX("\\textbf{D.} $pN/pS_{clonal}$")) +
    geom_hline(yintercept = 1, lty="dashed") +
    ylim(c(0,50)) +
    theme(plot.title = element_text(face = "bold", size=14))



```


```{r fig-time-lines, fig.height=13, fig.width=12}

ggpubr::ggarrange(panA,panB,panC,panD,panE,panF,panG,panH,panI, ncol=3, nrow=3, widths = c(2,2,2), common.legend = T,align = "hv")
```



# Supplementary figures


```{r}
plotVAF <- function(dt, ymax=30000) {
  q <- dt[1:100, 1:3000] %>% as.matrix %>% as.numeric
  spos <- dt[1,3002]
  sneg <- dt[1,3003]
  nq <- 100
  tFreqs <- data.frame(
    q = q,
    gene = factor(
      c(
        rep("driver", nq * 1000),
        rep("deleterious", nq * 1000),
        rep("neutral", nq * 1000)
      ),
      levels = c("driver", "neutral", "deleterious")
    ),
    mutation = factor(c(
      rep("N", nq * 500),
      rep("S", nq * 500),
      rep("N", nq * 500),
      rep("S", nq * 500),
      rep("N", nq * 500),
      rep("S", nq * 500)
    ),
    levels = c("N", "S"))
  )
  examplePNPS <-
    as.data.table(tFreqs)[q > 0, .N, by = c("gene", "mutation")] %>%
    dcast(gene ~ mutation) %>%
    mutate(pNpSall = N / S) %>%
    select(gene, pNpSall) %>%
    left_join(
      as.data.table(tFreqs)[q > 0.05, .N, by = c("gene", "mutation")] %>%
        dcast(gene ~ mutation) %>%
        mutate(pNpSdet = N / S) %>%
        select(gene, pNpSdet)
    ) %>%
    left_join(
      as.data.table(tFreqs)[q == 1, .N, by = c("gene", "mutation")] %>%
        dcast(gene ~ mutation) %>%
        mutate(pNpSclon = N / S) %>%
        select(gene, pNpSclon)
    )
  tFreqs %>%
    filter(q > 0) %>%
    ggplot(aes(x = q, fill = mutation)) +
    geom_bar(position = "stack") +
    scale_x_binned(breaks = seq(0.05,0.95, by = 0.05),
                   labels = c(".05","",".15","",".25","",".35","",".45","",".55","",".65","",".75","",".85","",".95"))+
    
    facet_wrap( ~ gene) +
    
    geom_text(
      data = examplePNPS,
      mapping = aes(
        x = 0.8,
        y = ymax,
        fill = NULL,
        label = latex2exp::TeX('$pN/pS_{all}$ = ', output = "character")
      ),
      vjust = 1,
      hjust = 1,
      size = 5,
      parse = T
    ) +
    geom_text(
      data = examplePNPS,
      mapping = aes(
        x = 0.8,
        y = ymax,
        fill = NULL,
        label = sprintf(" %.02f", pNpSall)
      ),
      vjust = 1,
      hjust = 0,
      size = 5,
      parse = T
    ) +
    geom_text(
      data = examplePNPS,
      mapping = aes(
        x = 0.8,
        y = 5*(ymax/6),
        fill = NULL,
        label = latex2exp::TeX('$pN/pS_{subclonal}$ = ', output = "character")
      ),
      vjust = 1,
      hjust = 1,
      size = 5,
      parse = T
    ) +
    geom_text(
      data = examplePNPS,
      mapping = aes(
        x = 0.8,
        y = 5*(ymax/6),
        fill = NULL,
        label = sprintf(" %.02f", pNpSdet)
      ),
      vjust = 1,
      hjust = 0,
      size = 5,
      parse = T
    ) +
    geom_text(
      data = examplePNPS,
      mapping = aes(
        x = 0.8,
        y = 4*(ymax/6),
        fill = NULL,
        label = latex2exp::TeX('$pN/pS_{clonal}$ = ', output = "character")
      ),
      vjust = 1,
      hjust = 1,
      size = 5,
      parse = T
    ) +
    geom_text(
      data = examplePNPS,
      mapping = aes(
        x = 0.8,
        y = 4*(ymax/6),
        fill = NULL,
        label = sprintf(" %.02f", pNpSclon)
      ),
      vjust = 1,
      hjust = 0,
      size = 5,
      parse = T
    ) +
    
    labs(
      x = "Frequency",
      y = "ocurrences in cohort",
      color = "mutation type",
      title=latex2exp::TeX(paste0("$s^+ = ",spos,"$, $s^- = ",sneg,"$"))
      
    ) +
    ggpubr::theme_pubr(base_size = 18) +
    theme(axis.text.x = element_text(
      angle = 45,
      vjust = 1,
      hjust = 1
    ))
}
```

```{r fig-supp1, warning=F, fig.width=14, fig.height=20}
#s_pos = 0.1
freq_files <- c(here::here("results/McF_30.freqs.csv"),here::here("results/McF_31.freqs.csv"),here::here("results/McF_32.freqs.csv"),here::here("results/McF_34.freqs.csv"),here::here("results/McF_33.freqs.csv"))
ggpubr::ggarrange(plotlist = lapply(freq_files,function(X){read_csv(X,col_names = F) %>% plotVAF(ymax=30000)}), common.legend = TRUE, legend = "top", ncol = 1 )
```

```{r fig-supp2, warning=F, fig.width=14, fig.height=20}
#s_pos = 0.5
freq_files <- c(here::here("results/McF_10.freqs.csv"),here::here("results/McF_11.freqs.csv"),here::here("results/McF_12.freqs.csv"),here::here("results/McF_14.freqs.csv"),here::here("results/McF_13.freqs.csv"))
ggpubr::ggarrange(plotlist = lapply(freq_files,function(X){read_csv(X,col_names = F) %>% plotVAF(ymax=18000)}), common.legend = TRUE, legend = "top", ncol = 1 )
```

```{r fig-supp3, warning=F, fig.width=14, fig.height=20}
#s_pos = 1
freq_files <- c(here::here("results/McF_20.freqs.csv"),here::here("results/McF_21.freqs.csv"),here::here("results/McF_22.freqs.csv"),here::here("results/McF_24.freqs.csv"),here::here("results/McF_23.freqs.csv"))
ggpubr::ggarrange(plotlist = lapply(freq_files,function(X){read_csv(X,col_names = F) %>% plotVAF(ymax = 16000)}), common.legend = TRUE, legend = "top", ncol = 1 )
```

```{r fig-supp4, warning=F, fig.width=14, fig.height=20}
#s_pos = 2
freq_files <- c(here::here("results/McF_40.freqs.csv"),here::here("results/McF_41.freqs.csv"),here::here("results/McF_42.freqs.csv"),here::here("results/McF_44.freqs.csv"),here::here("results/McF_43.freqs.csv"))
ggpubr::ggarrange(plotlist = lapply(freq_files,function(X){read_csv(X,col_names = F) %>% plotVAF(ymax = 16000)}), common.legend = TRUE, legend = "top", ncol = 1 )
```


